server:
    port: 8761

eureka:
    instance:
        # eureka实例的主机名
        hostname: euraka-server
    client:
        # 不把主机自己注册到eureka上
        register-with-eureka: false
        # 不从eureka上获取服务的注册信息
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/


